### PR TITLE
support dynamic query a list

### PR DESCRIPTION
**Pull request by jiangzm**
Fixes the third dynamic query.
```csharp
[TestMethod]
public void TestContainInQuery3()
{
    IList<Person> person = new List<Person> 
    {
        new Person{Name="123abcddd",Age=20},
        new Person{Name="456defeee",Age=21},
        new Person{Name="789abcfff",Age=22},
        new Person{Name="sdfsdfasd",Age=22}
    };

    //query ok
    var data1 = person.Where("Name.Contains(@0)", "abc").ToList();

    string[] array = new string[] { "123abcddd", "456defeee" };

    //query ok
    var data2 = person.Where("@0.Contains(Name)", array[0]).ToList();

    //query throw exception
    var data3 = person.Where("@0.Contains(Name)", (object)array).ToList();

    Assert.IsTrue(data3.Count == 2);
}
```
```csharp
public class Person
{
    public string Name { get; set; }
    public int Age { get; set; }
}
```

### CODE REVIEW

**Comment by ryanvgates** [comment]
Is this pull request associated with a bug? #19 is this pull request.

**Comment by jiangzm** [comment]
yes,fixed 'Contains' query.

**Comment by ryanvgates** [comment]
@jiangzm What is the issue #?

**Comment by jiangzm** [comment]
the issue #18

**Comment by ryanvgates** [comment]
@jiangzm Can you please include the unit tests on your pull request?

**Comment by ryanvgates** [comment]
@jiangzm the unit test passes with or without [the portion that you added](https://github.com/jiangzm/System.Linq.Dynamic/commit/7ba05030c5913b5d9b564970de2aeca7fce9980d). Can you fix it so that it would demonstrate bug and fail without your changes?

**Comment by jiangzm** [comment]
@ryanvgates The following expression tests do not pass.
```csharp
//query throw exception
var data3 = person.Where("@0.Contains(Name)", (object)array).ToList(); //array used as a param
```
The expression tests pass with [the portion that you added](https://github.com/jiangzm/System.Linq.Dynamic/commit/7ba05030c5913b5d9b564970de2aeca7fce9980d) . And the query result is right.

I verified in the `kahanu:master` branch still has this issue.

**Comment by ryanvgates** [comment]
I was able to verify that the tests fail on `kahanu:master`, but I do have a follow up question.

If I comment out the following [bit of code](https://github.com/jiangzm/System.Linq.Dynamic/blob/master/Src/System.Linq.Dynamic/DynamicLinq.cs#L1490-L1498), they pass. 

```csharp
if (methodName == "Contains")
{
	//for any method that acts on the parent element type, we need to specify the outerIt as scope.
	it = outerIt;
}
else
{
	it = innerIt;
}
```

Why would this be the case? Isn't this the core of the actual change that you made? Shouldn't they fail?

**Comment by ryanvgates** [comment]
I'm going to close this for now due to lack of activity.

**Pull request closed without merging**
