### PR TITLE
Join support

### PR DESCRIPTION
**Pull request by lennyf**
Code taken from stackoverflow answer

 http://stackoverflow.com/questions/389094/how-to-create-a-dynamic-linq-join-extension-method/412868#comment63039147_412868

### CODE REVIEW

**Comment by StefH** [comment]
Already implemented here:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicQueryableExtensions.cs#L440

**Comment by ryanvgates** [comment]
Is there an issue associated with this pull request? If not, can you create one explaining the issue? Can you add unit tests as well for the functionality?

**Comment by StefH** [comment]
There is no issue. I just wanted to tell that version from the library is much further in development : https://github.com/StefH/System.Linq.Dynamic.Core

**Comment by ryanvgates** [comment]
I didn't mean an issue with the code. I meant an issue in github to describe the functionality and how it should work.

**Comment by StefH** [comment]
Yes ok I see.

The issue would be like : Implement join as written on stackoverglow.

However this code is already present in my library.

**Comment by ryanvgates** [comment]
I'd need unit tests and an issue explaining the change to accept this @lennyf .

**Pull request closed without merging**
