### PR TITLE
Fixed #29. Updated ExpressionParser to parse numeric literals using invariant culture.

### LINKED ISSUE #29: Parsing of literals should use invariant culture
First of all, thanks for taking the initiative to improve the original dynamic LINQ!
One of the issues I always had with the original library is that it used the default Parse methods without passing in InvariantCulture.

This means that numeric strings may actually parse or not depending on the user's environment. This becomes more confusing because for some cultures, decimal places may be confused with other lexer tokens and so on. Code should always be parsed with InvariantCulture anyway!

### PR DESCRIPTION
**Pull request by glopesdev**
I used the default number styles for each TryParse overload and used invariant number info. Should be enough to avoid having the decimal place change depending on the current user's locale.

### CODE REVIEW

**Comment by ryanvgates** [comment]
@glopesdev Can you add some unit tests to demonstrate the error in #29?

**Comment by glopesdev** [comment]
Sure. Where do I add them? There is no unit test project. Shall I create one?
Or do you mean more informally just give an example here?

For the example to work you need to run the assembly under a culture different than "en-US" that uses "," (comma) as decimal separator, rather than "." (dot). When this happens, the parser will crash because it considers the (comma) as an argument separator rather than a decimal separator. And you can't use "." (dot) because float.Parse() crashes under the non-english culture.

Let me know how you want me to do this, or at least why you think my reasoning is not clear. I mean, I can add as many unit tests as you want, but in the end I think the fix is pretty easy: under C#, you need to parse floats with InvariantCulture. C# syntax does not change with your system culture. Neither should your scripting language. If there is something wrong with this reasoning, please tell me.

Otherwise, let me know where I put the unit tests and I will try to add them.

Best,

**Comment by glopesdev** [comment]
Ok, just noticed that a Test project was created. Thanks, I will add the unit tests there.

**Comment by glopesdev** [comment]
Ok, I've just pushed the unit tests. It was actually useful as I discovered a couple of TryParse calls that I missed on my first pass. Let me know if anything else is needed.

Also, is there a roadmap for when these fixes will be integrated into the NuGet package? It would be really useful to have this available.

**Comment by ryanvgates** [comment]
When I added just the unit tests to my local copy of System.Linq.Dynamic master branch, I wasn't able to see the unit tests that you added fail? Were you able to see them fail prior to the other code changes?

**Comment by glopesdev** [comment]
Yes, they do break in my system. Could it be that your system cannot load the "pt-PT" culture and then defaults to the system culture?

Can you check the value of the **Thread.CurrentThread.CurrentCulture** after the assignment in the Initialize method?

**Comment by ryanvgates** [comment]
I checked the **Thread.CurrentThread.CurrentCulture** and it is being set to `pt-PT`. I did notice that the value doesn't seem to be correct. In the case of the double test, it converts 1.0 to a double but the value is 10.0 rather than 1.0. The same thing is true for the float.

When your tests failed initially, what was the failure message? Can you add additional criteria to the test to make it fail (e.g. checking the value)?

**Comment by glopesdev** [comment]
My tests initially failed with a parse exception so I never got to see inconsistent values. Interesting, so this means that culture issues manifest differently from system to system... All the more reason to use **InvariantCulture** everywhere!

I've added unit tests to check the value of the parsed expression. Can you check that they break in your system? Apparently, they don't break in my configuration, so there is no way for me to go further in this.

**Comment by glopesdev** [comment]
Any news on this pull request? Let me know if there is anything else you think needs to be done.

**Comment by ryanvgates** [comment]
Sorry about the delay, lots of other things going on. Everything looks good now. Thank you for adding the value check to the unit tests.

**Pull request merged**
