### PR TITLE
Fixed #31. Removed predefined type check on member method access.

### LINKED ISSUE #31: Calling instance methods does not work unless the type is a predefined type
This is also another feature that I never understood. There is an explicit check in ```ParseMemberAccess``` that blocks calling any methods if the class is not part of the predefined types (i.e. int, float, Math, etc).

This makes no sense, because it means I can call ```ToString``` if the input is a number, but not if the input is a ```Point```.

I say this check should simply be removed.

### PR DESCRIPTION
**Pull request by glopesdev**
Also removed the ```IsPredefinedType``` method altogether since it was not used anywhere else. It also used an explicit foreach implementation rather than ```Contains``` for some unknown reason.

### CODE REVIEW

**Comment by ryanvgates** [comment]
Is this in reference to an issue? Why did it need to be removed?

**Comment by kahanu** [comment]
I didn't remove it.  I don't think anything should be removed, but rather a fix should be added to preserve legacy applications.

**Comment by glopesdev** [comment]
I'm sorry if this caused confusion. I opened a [related issue](https://github.com/kahanu/System.Linq.Dynamic/issues/31) and submitted a pull-request to fix it. The fix is fully backwards compatible and no functionality was removed.

What happens is that on the original 2008 implementation, for some reason the possibility of calling method instances was blocked from all types except the predefined types (e.g. int, Math, Convert, etc).

This leads to the awkward situation where you can call ```ToString``` on an integer object, but you cannot call it on ```Point``` instances or any other class. I always thought this made no sense. Legacy applications will all work. This is a case where removing a check actually enables more functionality rather than less.

The reason I removed the ```IsPredefinedType``` method entirely is because nothing else in the code used it and it was a private static method.

**Comment by ryanvgates** [comment]
@glopesdev Can you please add some unit tests to this pull request under the System.Linq.Dynamic.Test project?

**Comment by glopesdev** [comment]
I've just pushed a unit test for this issue.

**Comment by glopesdev** [comment]
Thanks for merging the last pull request. I would love to also get this one in before the next NuGet release. Feel free to feedback on any missing tests or clarifications.

**Pull request merged**
