### PR TITLE
Adding sample queries

### PR DESCRIPTION
**Pull request by ryanvgates**
Adding documentation to the repository for issue #8.

### CODE REVIEW

**Comment by ryanvgates** [comment]
@kahanu did you ever have a chance to review this changeset? Or consider this option of adding the samples directly to the repo? This way the samples will be indexed and easier to find through searching.

**Comment by kahanu** [comment]
@ryanvgates - sorry no I haven't.  The company I'm working with has added a fourth project to my workload.  I have very little time for anything.  Until I have more breathing room, do you feel comfortable making these decisions?

**Comment by ryanvgates** [comment]
@kahanu sure, no problem. I'm going to move forward with the general theme of adding in the samples. We can always change direction later.

**Comment by kahanu** [comment]
@ryanvgates thanks, I really appreciate the help maintaining this project.

**Comment by ryanvgates** [comment]
@kahanu no problem. I'm happy to do it. I think it's a great project.

**Pull request merged**
