### PR TITLE
Overwrite Message rather than ToString()

### PR DESCRIPTION
**Pull request by ryanvgates**
Fixed the code to overwrite Message rather than ToString() since ToString() should include excpetion information

Removing bin, obj, suo

Added a gitignore file

This is to resolve issue #24

### CODE REVIEW

**Comment by kahanu** [comment]
Hi Ryan, it looks like you are removing the toString() method and replacing it with the Message property.  Is that what you are doing?  If so, I don't think anything should be removed.  If I'm wrong in what I see in the changed files, let me know.  I haven't examined the actual source code.

**Comment by ryanvgates** [comment]
@kahanu I'm just making it so that the toString() method will use the base one from [Exception.](https://msdn.microsoft.com/en-us/library/system.exception.tostring%28v=vs.110%29.aspx) There would still be a toString() method that would include the message. One of the issues I had with the original code is that it's an exception, but toString() doesn't give you the stack trace or other details that are very helpful in debugging.

**Comment by ryanvgates** [comment]
@kahanu do you mind if I merge the pull request? Should I close this?

**Comment by kahanu** [comment]
@ryanvgates - if you don't think it will affect existing users upgrading to this version, then you can merge it.

**Comment by ryanvgates** [comment]
I'm going to close this for now then, as it would impact current users that upgrade. The ToString() would be far more verbose, which is fine for debugging but if they are using it for the UI then it would be a problem.

**Pull request closed without merging**
